package com.serverless.data;

import com.amazonaws.services.dynamodbv2.datamodeling.*;

import java.time.Instant;

/**
 * @author ragesh shunmugam
 */
@DynamoDBTable(tableName = "user")
public class User {

    @DynamoDBHashKey(attributeName = "userId")
    private String userName;
    @DynamoDBAttribute(attributeName = "orgUsername")
    private String orgUsername;
    @DynamoDBAttribute(attributeName = "organisation")
    private String organisation;
    @DynamoDBAttribute(attributeName = "currentLoginDate")
    @DynamoDBAutoGeneratedTimestamp(strategy = DynamoDBAutoGenerateStrategy.ALWAYS)
    private String currentLoginDate;
    @DynamoDBAttribute(attributeName = "lastLoginDate")
    @DynamoDBAutoGeneratedTimestamp(strategy = DynamoDBAutoGenerateStrategy.CREATE)
    private String lastLoginDate;

    public User() {

    }

    public void setCurrentLoginDate(final String currentLoginDate) {
        this.currentLoginDate = currentLoginDate;
    }

    public String getUserName() {
        return userName;
    }

    public String getOrganisation() {
        return organisation;
    }

    public String getCurrentLoginDate() {
        return currentLoginDate;
    }

    public String getLastLoginDate() {
        return lastLoginDate;
    }

    public void setLastLoginDate(String lastLoginDate) {
        this.lastLoginDate = lastLoginDate;
    }

    public String getOrgUsername() {
        return orgUsername;
    }

    public void setOrgUsername(String orgUsername) {
        this.orgUsername = orgUsername;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public void setOrganisation(String organisation) {
        this.organisation = organisation;
    }

    @Override
    public String toString() {
        return "User{" +
                "userName='" + userName + '\'' +
                ", orgUsername='" + orgUsername + '\'' +
                ", organisation='" + organisation + '\'' +
                ", currentLoginDate=" + currentLoginDate +
                ", lastLoginDate=" + lastLoginDate +
                '}';
    }
}